name: grabcss
services:
  grabcss:
    image: grabcss
    container_name: grabcss
    build:
      context: ..
      dockerfile: dev/Dockerfile
    command: /bin/bash -c 'cd dev && pnpm dev'
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ..:/grabcss
